FROM node:12.13-alpine As temp

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build


FROM node:12.13-alpine as production

ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm i -g yarn
RUN yarn install --production

COPY .env.${NODE_ENV} ./.env
COPY . .

COPY --from=temp /usr/src/app/dist ./dist

COPY start.sh /
RUN chmod +x /start.sh

CMD ["/start.sh"]