FROM node:12.13-alpine As development

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build


FROM node:12.13-alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --only=production

COPY . .
COPY .env.${NODE_ENV} ./.env

COPY --from=development /usr/src/app/dist ./dist

#RUN typeorm migration:run <name>

CMD ["node", "dist/main"]