version: 2
jobs:
  test:
    docker:
      - image: node:12.13-alpine

    working_directory: ~/usr/src/app

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm i -g yarn
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn typeorm migration:generate -n init
      - run: yarn typeorm migration:run

      # run tests!
      - run: yarn test:e2e-ci

  deploy:
    docker:
      - image: node:12.13-alpine

    working_directory: ~/usr/src/app

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm i -g yarn
      - run: yarn install
      - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
      - run: apk add --no-cache curl
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.3-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: yarn ci:docker

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          context: voicy
      - deploy:
          context: voicy
          requires:
            - test
