version: 2
jobs:
  test:
    docker:
      - image: node:12.13-alpine

    working_directory: ~/usr/src/app

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn typeorm migration:generate -n init
      - run: yarn typeorm migration:run
      #!add rollback!
      - run: yarn test:e2e-ci

  build:
    docker:
      - image: alpine:3.7

    steps:
      - checkout
      - setup_remote_docker
      - run: apk add --no-cache curl
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.3-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin/
      - run: docker build -t artgurianov/voicy:latest --no-cache .
      - run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run: docker push artgurianov/voicy:latest

  deploy:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run: apk add --no-cache openssh
      - add_ssh_keys:
          fingerprints:
            - '75:7d:01:a4:aa:07:4e:c7:08:47:77:b1:c6:f0:13:9b'
      #- run: ssh-keyscan -H 164.90.224.15 >> ~/.ssh/known_hosts
      - run: ssh root@164.90.224.15

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test:
          context: voicy
      - build:
          context: voicy
          requires:
            - test
      - deploy:
          context: voicy
          requires:
            - test
            - build
