name: CI/CD
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run the linter
      run: yarn lint

  # TODO: cache node_modules between jobs
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run unit tests
      run: yarn test:unit
    # - name: Run e2e tests
    #   run: yarn test:e2e

